# Generated by Django 5.0.7 on 2024-08-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
