# Generated by Django 5.0.7 on 2024-08-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_product_image', '0001_initial'),
        ('src_product_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src_product_items.productitems'),
        ),
    ]
