# Generated by Django 5.0.7 on 2024-08-23 18:17

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_product_items', '0001_initial'),
        ('src_size_option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('qty_in_stock', models.BigIntegerField(default=0)),
                ('edited', models.BooleanField(default=False)),
                ('product_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_product_items.productitems')),
                ('size_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_size_option.sizeoption')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
