# Generated by Django 5.0.7 on 2024-09-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_product_variation', '0002_alter_productvariation_size_option'),
        ('src_size_option', '0002_sizeoption_size_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size_option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src_size_option.sizeoption'),
        ),
    ]
