# Generated by Django 5.0.7 on 2024-08-28 16:23

import src.product_category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_product_category', '0002_productcategory_size_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=src.product_category.models.category_directory_path),
        ),
    ]
