# Generated by Django 5.0.7 on 2024-09-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_product_category', '0004_alter_productcategory_size_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_image',
        ),
    ]
