# Generated by Django 5.0.7 on 2024-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
