# Generated by Django 5.0.7 on 2024-09-18 17:36

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_orders', '0001_initial'),
        ('src_product_items', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('edited', models.BooleanField(default=False)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_orders.orders')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src_product_items.productitems')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
