# Generated by Django 5.0.7 on 2024-09-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_order_items', '0001_initial'),
        ('src_product_variation', '0002_alter_productvariation_size_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src_product_variation.productvariation'),
        ),
    ]
