# Generated by Django 5.0.7 on 2024-08-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_product_items', '0001_initial'),
        ('src_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_products.products'),
        ),
    ]
