# Generated by Django 5.0.7 on 2024-09-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_orders', '0002_orders_cus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
