# Generated by Django 5.0.7 on 2024-09-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_orders', '0003_orders_ispaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Chưa thanh toán', max_length=255),
        ),
    ]
