# Generated by Django 5.0.7 on 2024-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_orders', '0004_remove_orders_ispaid_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
